# Fundamentals of Numpy Arrays

In [2]:
import numpy as np

## Numpy N-dimesional Array
- Able to take a Python list and transform into an array

In [ ]:
# create list of floating point values
float_list = [1.0, 2.0, 3.0]

# transform list into a ndarray
list_to_array = np.array(float_list)

# print array
print(list_to_array)

# print array shape
print(list_to_array.shape)

# print array data type
print(list_to_array.dtype)

<hr>

## Functions to Create Arrays

### Empty Array

In [11]:
# create an empty (3x3) 2-D array
empty_array = np.empty((3,3))

# print empty array
print(empty_array)

[4.01407985e-31 1.08380156e-30 6.22182376e-31]


An important note is that this array is not truly empty, but contains random contents that have to be assigned before using it. 

In [12]:
for num in empty_array:
    print(num)

4.01407984641058e-31
1.083801558530856e-30
6.221823761936385e-31


### Zeros Array

In [13]:
# create a (3x5) 2-D array filled with zeros
zeros_array = np.zeros((3,5))

# print zeros_array
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones Array

In [14]:
# create a (5x1) 1-D array filled with ones
ones_array = np.ones((5))

# print ones_array
print(ones_array)

[1. 1. 1. 1. 1.]


<hr>

## Combining Arrays

### Vertical Stack

In [16]:
# create first array
array_1 = np.array([1,2,3])
print(array_1)

# create second array
array_2 = np.array([4,5,6])
print(array_2)

# vertical stack both arrays
vertical_array = np.vstack((array_1, array_2))
print(vertical_array)
print(vertical_array.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


### Horizontal Stack

In [ ]:
# create first array
array_1 = np.array([1,2,3])
print(array_1)

# create second array
array_2 = np.array([4,5,6])
print(array_2)

# horizontal stack both arrays
horizontal_array = np.hstack((array_1, array_2))
print(horizontal_array)
print(horizontal_array.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


<hr>

# Index, Slice, and Reshape Arrays

## Python Lists to Arrays

In [39]:
# combining two lists together into a 2-D array
# generate two random lists of five numbers
import random
random.seed(123)

list_1 = list()
list_2 = list()


for num in range(5):
    list_1.append(random.randint(0,100))
    list_2.append(random.randint(0,100))

print(list_1)
print(list_2)
print('\n')

############################

# method 1
print('method 1')

# transform lists to nd_array
list_1_array = np.array(list_1)
print(list_1_array)
print(list_1_array.dtype)

list_2_array = np.array(list_2)
print(list_2_array)
print(type(list_2_array))

# vertical stack arrays to form 2-D array
vstack_array = np.vstack((list_1_array, list_2_array))
print(vstack_array)
print(vstack_array.dtype)
print(vstack_array.shape)
print('\n')

############################

# method 2
print('method 2')
new_list = list()
new_list.append(list_1)
new_list.append(list_2)
print(new_list)
new_array = np.array(new_list)
print(new_array)
print(new_array.dtype)
print(new_array.shape)

[6, 11, 52, 13, 48]
[34, 98, 34, 4, 68]


method 1
[ 6 11 52 13 48]
int64
[34 98 34  4 68]
<class 'numpy.ndarray'>
[[ 6 11 52 13 48]
 [34 98 34  4 68]]
int64
(2, 5)


method 2
[[6, 11, 52, 13, 48], [34, 98, 34, 4, 68]]
[[ 6 11 52 13 48]
 [34 98 34  4 68]]
int64
(2, 5)


<hr>

## Array Indexing